In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'I support real madrid',
     'i play football',
     'real madrid win three UCL in roe',
    'romos was captain of real madrid',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
voc_size=100

**one hot represenatation**

one_hot() is inbuild function of keras

we should pass word and voc_size

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[76, 69, 72, 58], [76, 65, 1], [72, 58, 93, 2, 3, 46, 1], [37, 35, 29, 94, 72, 58], [76, 82, 58, 97, 76], [99, 53, 69, 94, 11], [30, 77, 87, 97]]


**Word Embedding Represntation**

for making word embedding matrix we have to give dimensions means no of features

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences    # all sentense should have same lenght sentense
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [8]:
sent_length=8      # max sentense length
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) # one_hot_repe, pre padding applied in front of sentense
print(embedded_docs)

[[ 0  0  0  0 76 69 72 58]
 [ 0  0  0  0  0 76 65  1]
 [ 0 72 58 93  2  3 46  1]
 [ 0  0 37 35 29 94 72 58]
 [ 0  0  0 76 82 58 97 76]
 [ 0  0  0 99 53 69 94 11]
 [ 0  0  0  0 30 77 87 97]]


In [9]:
dim=10   # feature dimension

In [11]:
model=Sequential()    # making sequential model
model.add(Embedding(voc_size,10,input_length=sent_length)) # adding layers we have to give (voc size,dimension,max legth)
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             1000      
Total params: 1,000
Trainable params: 1,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[-4.71565127e-02  4.78708632e-02  3.76407020e-02  7.78364018e-03
   -4.51791063e-02 -5.67020103e-03  2.86571495e-02  1.70604102e-02
   -4.46399711e-02 -2.52069719e-02]
  [-4.71565127e-02  4.78708632e-02  3.76407020e-02  7.78364018e-03
   -4.51791063e-02 -5.67020103e-03  2.86571495e-02  1.70604102e-02
   -4.46399711e-02 -2.52069719e-02]
  [-4.71565127e-02  4.78708632e-02  3.76407020e-02  7.78364018e-03
   -4.51791063e-02 -5.67020103e-03  2.86571495e-02  1.70604102e-02
   -4.46399711e-02 -2.52069719e-02]
  [-4.71565127e-02  4.78708632e-02  3.76407020e-02  7.78364018e-03
   -4.51791063e-02 -5.67020103e-03  2.86571495e-02  1.70604102e-02
   -4.46399711e-02 -2.52069719e-02]
  [ 3.57430093e-02 -4.18879874e-02 -1.29374042e-02  4.01444323e-02
    3.04859877e-03 -2.43299250e-02  1.38083585e-02  3.11783887e-02
    3.97630781e-03 -3.60802300e-02]
  [ 3.55225839e-02 -1.27484910e-02  3.22872661e-02  5.57208061e-03
    2.83460058e-02 -2.71888264e-02  2.47458108e-02 -4.39400077e-02
   -4.94587198e-

In [15]:
embedded_docs[0] # 1st sentense

array([ 0,  0,  0,  0, 76, 69, 72, 58], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])  # word embedding for 1st sentense

[[-4.71565127e-02  4.78708632e-02  3.76407020e-02  7.78364018e-03
  -4.51791063e-02 -5.67020103e-03  2.86571495e-02  1.70604102e-02
  -4.46399711e-02 -2.52069719e-02]
 [-4.71565127e-02  4.78708632e-02  3.76407020e-02  7.78364018e-03
  -4.51791063e-02 -5.67020103e-03  2.86571495e-02  1.70604102e-02
  -4.46399711e-02 -2.52069719e-02]
 [-4.71565127e-02  4.78708632e-02  3.76407020e-02  7.78364018e-03
  -4.51791063e-02 -5.67020103e-03  2.86571495e-02  1.70604102e-02
  -4.46399711e-02 -2.52069719e-02]
 [-4.71565127e-02  4.78708632e-02  3.76407020e-02  7.78364018e-03
  -4.51791063e-02 -5.67020103e-03  2.86571495e-02  1.70604102e-02
  -4.46399711e-02 -2.52069719e-02]
 [ 3.57430093e-02 -4.18879874e-02 -1.29374042e-02  4.01444323e-02
   3.04859877e-03 -2.43299250e-02  1.38083585e-02  3.11783887e-02
   3.97630781e-03 -3.60802300e-02]
 [ 3.55225839e-02 -1.27484910e-02  3.22872661e-02  5.57208061e-03
   2.83460058e-02 -2.71888264e-02  2.47458108e-02 -4.39400077e-02
  -4.94587198e-02  8.64208862e-03